=== commology/wismon/etc/wismon_schema_events.json
{
    "type":"object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "id": "http://jsonschema.net",
    "required":false,
    "properties":{
        "centre": {
            "type":"string",
            "id": "http://jsonschema.net/centre",
            "required":true
        },
        "events": {
            "type":"array",
            "id": "http://jsonschema.net/events",
            "required":true,
            "items": {
                    "type":"object",
                    "id": "http://jsonschema.net/events/0",
                    "required":true,
                    "properties":{
                        "end": {
                            "type":"string",
                            "id": "http://jsonschema.net/events/0/end",
                            "required":true
                        },
                        "id": {
                            "type":"number",
                            "id": "http://jsonschema.net/events/0/id",
                            "required":true
                        },
                        "start": {
                            "type":"string",
                            "id": "http://jsonschema.net/events/0/start",
                            "required":true
                        },
                        "text": {
                            "type":"string",
                            "id": "http://jsonschema.net/events/0/text",
                            "required":true
                        },
                        "title": {
                            "type":"string",
                            "id": "http://jsonschema.net/events/0/title",
                            "required":true
                        }
                    }
                }
        },
        "timestamp": {
            "type":"string",
            "id": "http://jsonschema.net/timestamp",
            "required":true
        },
        "wmo_wis_monitoring": {
            "type":"string",
            "id": "http://jsonschema.net/wmo_wis_monitoring",
            "required":true
        }
    }
}

=== commology/wismon/etc/wismon_templ_events.json
{
    "wmo_wis_monitoring": "1.0",
    "centre": "GISC Beijing",
    "timestamp": "2014-11-10T00:00:00Z",
    "events" : 
    [
        {
            "id" : 1,
            "title" : "GISC Beijing Development Maintenance",
            "text" : "This is test message only for monitoring pilot test",
            "start" : "2015-06-01T00:00:00Z",
            "end" : "2015-06-01T02:00:00Z"
        }
    ]
}
